export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const SEARCH_POSTS_REQUEST = "SEARCH_POSTS_REQUEST";
export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS";
export const SEARCH_POSTS_FAILURE = "SEARCH_POSTS_FAILURE";

export const GET_POPULAR_SUBS_REQUEST = "GET_POPULAR_SUBS_REQUEST";
export const GET_POPULAR_SUBS_SUCCESS = "GET_POPULAR_SUBS_SUCCESS";
export const GET_POPULAR_SUBS_FAILURE = "GET_POPULAR_SUBS_FAILURE";
