name: Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REACT_APP_API_URL: ${{secrets.API_URL}}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install packages
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Rename index file
        run: mv build/index.html build/200.html

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to surge
        run: surge ./build lurkershub.surge.sh --token ${{secrets.SURGE_TOKEN}}
